# Cookies配置文件
# 支持的平台及其cookies文件配置

platforms:
  douyin:
    name: "抖音"
    cookies_file: "douyin.txt"
    required: true
    check_interval: 3600  # 检查间隔(秒) - 1小时
    expiry_warning_days: 3  # 过期前几天开始提醒
    
  bilibili:
    name: "哔哩哔哩"
    cookies_file: "bilibili.txt"
    required: false
    check_interval: 7200  # 2小时
    expiry_warning_days: 7
    
  xiaohongshu:
    name: "小红书"
    cookies_file: "xiaohongshu.txt"
    required: false
    check_interval: 3600
    expiry_warning_days: 5

# 通知配置
notifications:
  enabled: true
  methods:
    - "log"      # 日志记录
    - "file"     # 文件记录
    - "webhook"  # Webhook通知（企微机器人）
  
  log_level: "WARNING"
  notification_file: "cookies_notifications.log"
  
  # Webhook配置（企微机器人）
  webhook_url: ""  # 请填入企微机器人的Webhook URL
  # 示例: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=your_key_here"

# 检查配置
health_check:
  enabled: true
  startup_check: true    # 启动时检查
  periodic_check: true   # 定期检查
  check_on_error: true   # 出错时检查
